#+TITLE: My configurations of spacemacs
* Quick installation
** STEP 1: download Emacs
checkout[[https://github.com/syl20bnr/spacemacs][ spacemacs github page]] Prerequisites section to download Emacs based on your system
** STEP 2: clone .emacs.d (spacemacs repository)
follow the instruction in the install section to clone the .emacs.d folder into your home path
** STEP 3: clone .spacemacs.d (this repository) 
clone this repository into your home path as well.(run the following code in your terminal)
#+BEGIN_SRC sh
git clone https://github.com/Peter-Chou/spacemacs-repository.git ~/.spacemacs.d
#+END_SRC
** ALMOST THERE: launch Emacs
Finally, Lauch the emacs for the initial configuration, it will automatically download all the 
necessary packages and you are ready to go.
** TIPS
In this configuration, The Emacs server will be run as a demon process when you launch Emacs.

It can be super fast when using Emacs client to recall the closed Emacs or open a file with Emacs.

Do not start Emacs launcher again once you've done that, It will open another Emacs and may has some
onflictions with the existing server.

You should put these two commands in your .bash_profile / .bashrc to use this tip at ease.
#+BEGIN_SRC sh
alias e="emacsclient -n"
alias ec="emacsclient -n -c"
#+end_src
if you close your Emacs frame, you can recall the Emacs by typing ~ec~ in your terminal.

you can open a file (e.g. foo.py in your current directory) by typing ~e foo.py~ in your terminal.
