;;; ayu-theme.el --- an Emacs 24 theme based on ayu (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1484521107
;;; Original author: Ike Ku
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from ayu (tmTheme) by Ike Ku
;;
;;; Code:

(deftheme ayu
  "ayu-theme - Created by tmtheme-to-deftheme - 2017-01-15 15:58:27 -0700")

(custom-theme-set-variables
 'ayu
 )

(custom-theme-set-faces
 'ayu
 ;; basic theming.

 '(default ((t (:foreground "#D9D7CE" :background "#212733" ))))
 '(region  ((t (:background "#343F4C"))))
 '(cursor  ((t (:background "#FFCC66"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#bbdda8"  :background "#333942" ))))
 '(fringe                              ((t (                       :background "#333942" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "#95E6CB"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground nil   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                       :background "#242B38" :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#b4b09e"  :background "#333942" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#ff7727"  :background "#333942" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))

 ;; company-mode
 '(company-tooltip ((t (:foreground "#dcdccc" :background "#303a4c"  ))))
 '(company-tooltip-annotation ((t (:foreground "#FFAE57" :background "#303a4c"  ))))
 '(company-tooltip-annotation-selection ((t (:foreground "#FFAE57" :background "#303a4c"  ))))
 '(company-tooltip-selection ((t (:foreground "#dcdccc" :background "#313335"  ))))
 '(company-tooltip-mouse ((t (:background "#303a4c"))))
 '(company-tooltip-common ((t (:foreground "#ff7727"))))
 '(company-scrollbar-fg ((t (:background "#313335"))))
 '(company-scrollbar-bg ((t (:background "#303a4c"))))
 '(company-preview ((t (:background "#ff7727"))))
 '(company-preview-common ((t (:foreground "#ff7727" :background "#303a4c"))))

 ;; iedit-mode
 '(iedit-occurrence ((t (:background "#61b0b7" :weight bold))))

 ;; ruler-mode
 '(ruler-mode-fill-column ((t (:inherit 'ruler-mode-default :foreground "#ffec49"))))

 '(font-lock-comment-face ((t (:foreground "#5C6773"  :italic t))))
 '(font-lock-variable-name-face ((t (:foreground "#ffec49"  )))) ;; #36a3d9
 '(font-lock-keyword-face ((t (:foreground "#ff7727"  :bold t))))
 '(font-lock-constant-face ((t (:foreground "#ffffff"  :bold t))))
 '(font-lock-function-name-face ((t (:foreground "#FFAE57"  :bold t))))
 '(font-lock-builtin-face ((t (:foreground "#FFAE57"  ))))
 '(font-lock-string-face ((t (:foreground "#BAE67E"  :normal t))))
 '(font-lock-type-face ((t (:foreground "#5CCFE6"  :bold t))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" :background "#FFAE57" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5C6773"  :italic t))))

 '(diff-added ((t (:foreground "#BAE67E"  ))))
 '(diff-removed ((t (:foreground "#5CCFE6"  ))))
 '(diff-changed ((t (:foreground "#FFAE57"  ))))

 '(markdown-list-face ((t (:foreground "#D9D7CE"  ))))
 '(markdown-blockquote-face ((t (:foreground "#80D4FF"  :italic t))))
 '(markdown-link-title-face ((t (:foreground "#FFC44C"  :underline t))))

 '(git-gutter:untracked ((t (:foreground "#5C6773"  ))))
 '(git-gutter:deleted ((t (:foreground "#5CCFE6"  ))))

 ;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#dcdccc"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#ff7727"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#ffec49"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#36a3d9"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#dcdccc"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#ff7727"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#ffec49"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#36a3d9"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#dcdccc"))))
 '(rainbow-delimiters-depth-10-face ((t (:foreground "#ff7727"))))
 '(rainbow-delimiters-depth-11-face ((t (:foreground "#ffec49"))))
 '(rainbow-delimiters-depth-12-face ((t (:foreground "#36a3d9"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))

 ;; smartparens
 '(sp-show-pair-mismatch-face ((t (:foreground "#FF0000" :background "#36a3d9" :weight bold))))
 '(sp-show-pair-match-face ((t (:background "#36a3d9" :weight bold))))

 ;; highlight-indentation
 '(highlight-indentation-current-column-face ((t (:background "#ffec49"))))
 ) ;; End face definitions



;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'ayu)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; ayu-theme.el ends here
